### ISSUE TITLE
Potential issue

### ISSUE THREAD

**Issue by luckman212** [Johnson0907/obsidian-file-cleaner#1]
Hi @Johnson0907 

Nice idea for a plugin! Just want to throw out a word of caution: due to [this](https://forum.obsidian.md/t/0-byte-file-again-note-completely-destroyed-v0-13-19-installer-0-13-14/30000) (as far as I know still unrersolved) bug, Mac users might want to be extra careful when using it.

**Comment by Johnson0907** [comment]
Thanks， this is a very important piece of information.
