### ISSUE TITLE
The image is actually referenced, but will be treated as unreferenced, resulting in accidental deletion.

### ISSUE THREAD

**Issue by tyf2018** [Johnson0907/obsidian-file-cleaner#2]
Hi，

If using the admonition plugin, use the following code to reference the image. The image is actually referenced, but will be treated as unreferenced, resulting in accidental deletion.

`````
````ad-灵感
collapse: open
title: 测试
![[202008271317.png]]
````
`````

Looking forward to your reply!
Best regards.

**Comment by Johnson0907** [comment]
Thanks for your report. I am sorry about the inconvenience caused.
The plugin used the official API `resolvedLinks` to get backlinks, but links in admonition code blocks cannot be recognized by this api.
This issue can only wait for the official update API, or I will fix it in other ways.

**Comment by Johnson0907** [comment]
After 0.14.0, Obsidian added a new feature Callout (also known as Admonition).
The image referenced in Callout can be identified.
More info at https://help.obsidian.md/Use+callouts.
