### ISSUE TITLE
Global setting for excluded folders.

### ISSUE THREAD

**Issue by An-qi-Zhang** [Johnson0907/obsidian-file-cleaner#3]
Thank you for your good work in this plugin!

I wonder if the user can type down the excluded folders that the file cleaning does not touch.

**Comment by Johnson0907** [comment]
Thank you for your feedback.
It's a pretty nice feature, unfortunately not yet, but I'll consider adding it.

**Comment by johnsonhong997** [comment]
The latest version supports "Excluded Folders".
